### ISSUE TITLE
萤石摄像头固件修改的问题

### ISSUE THREAD

**Issue by 77clearlove** [Ovi3/ezviz_firmware_parser#1]
你好，我用了一下你提供的萤石摄像头固件解压脚本。修改固件并重打包，利用摄像头升级功能成功进行了升级，但升级之后设备变砖。
用串口连接进行分析得知，bootload在校验新写入的app.img校验失败，导致无法挂载文件系统，设备无法正常运行。
我想问一下你是否使用过该脚本？如果可以的话希望能够交流一下。非常感谢！

**Comment by Ovi3** [comment]
不好意思，时隔多年已经忘了，也没做过重打包并升级的操作，也没逆向过bootloader校验逻辑。
